services:
  typebot-builder:
    container_name: typebot-builder
    image: baptistearno/typebot-builder:latest
    restart: always

    ports:
      - '8083:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    networks:
      - caddy_network

  typebot-viewer:
    container_name: typebot-viewer
    image: baptistearno/typebot-viewer:latest

    restart: always
    ports:
      - '8084:3000'
    env_file: .env
    networks:
      - caddy_network

volumes:
  db-data:

networks:
  caddy_network:
    external: true